export const AUTHENTICATE_THE_USER = 'AUTHENTICATE_THE_USER'
export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_IN = 'SIGN_IN'
export const GET_USER = 'GET_USER'
export const GET_WALLET = 'GET_WALLET'